import type { Metadata } from "next";
import { Toaster } from 'sonner';
import { Montserrat, } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/components/NavBar";
// import { userLogOut, userLogIn, userRegister} from '@/app/lib/userLogic'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href='../public/favicon.ico' type="image/x-icon" />
        <title>SnapEvent</title>
      </head>
      <body className={`${inter.className}`}>
        <NavBar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
